version: "3.8"
services:
  transaction-validator:
    build:
      context: .
    image: transaction-validator:prod
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
