version: '3.8'
services:
  # Green instance
  tv_green:
    build: ../microservice
    container_name: tv_green
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
    command: ["python","app.py","--port=5001"]

  # Blue instance
  tv_blue:
    build: ../microservice
    container_name: tv_blue
    environment:
      - PORT=5002
    ports:
      - "5002:5002"
    command: ["python","app.py","--port=5002"]

  # Simple Nginx LB to switch traffic via config
  nginx:
    image: nginx:stable
    container_name: nginx-lb
    volumes:
      - ./nginx-lb.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - tv_green
      - tv_blue

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  # Grafana (user/pass admin/admin)
  grafana:
    image: grafana/grafana-oss:10.1.5
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  # Loki (logs)
  loki:
    image: grafana/loki:2.8.2
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
    ports:
      - "3100:3100"

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.49
    ports:
      - "16686:16686"
      - "14268:14268"
